apiVersion: apps/v1
kind: Deployment
metadata:
  name: qazwsx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qazwsx
  template:
    metadata:
      labels:
        app: qazwsx
    spec:
      containers:
      - image: okteto.dev/qazwsx:latest
        name: qazwsx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a72d8513-0fa3-43a6-983c-f0034f2d6253"
        - name: Vless_Path
          value: "/vl45rfd7"
        - name: Vmess_UUID
          value: "a72d8513-0fa3-43a6-983c-f0034f2d6253"
        - name: Vmess_Path
          value: "/vm89emuj0"
        - name: Share_Path
          value: "/v2link"
